base_config: configs/supervised_wilds_vith14_ep300-lp.yaml

constants:
  logging.write_tag: linear_probe

grid:
  optimization.optimizer: [adamw, lars, sgd]
  optimization.lr: [0.01, 0.05]
  optimization.weight_decay: [5.0e-4]
  optimization.momentum: [0.9, 0.5]
  optimization.lr_schedule: [cosine, step]
  data.batch_size: [32, 64, 512]
  meta.probe_type: [linear, mlp]
  meta.mlp_hidden_dim: [1024]
  meta.dropout: [0.0]

launch:
  folder: submitit_logs/
  partition: gpu1
  nodes: 1
  tasks_per_node: 1
  time: 180
