base_config: configs/supervised_wilds_vitb16-448_ep600-lp.yaml

constants:
  logging.write_tag: linear_probe

grid:
  optimization.optimizer: [adamw]
  optimization.lr: [0.01]
  optimization.weight_decay: [5.0e-4]
  optimization.momentum: [0.9, 0.99]
  optimization.lr_schedule: [cosine]
  data.batch_size: [128, 256]
  meta.probe_type: [mlp, linear]
  meta.mlp_hidden_dim: [512, 1024, 2048]
  meta.dropout: [0.0, 0.1, 0.3]

launch:
  folder: submitit_logs/
  partition: gpu1
  nodes: 1
  tasks_per_node: 1
  time: 180
