base_config: configs/supervised_wilds_vitb16-448_ep600-lp.yaml

constants:
  logging.write_tag: linear_probe

grid:
  optimization.optimizer: [adamw]
  optimization.lr: [0.01, 0.05, 0.001]
  optimization.weight_decay: [5.0e-4, 0]
  optimization.momentum: [0.9, 0.99, 0.5]
  optimization.lr_schedule: [cosine, step]
  data.batch_size: [32, 64, 128, 256]
  meta.representation_type: [last_avgpool, last4_avgpool_concat]
  meta.head_type: [linear, bn_linear]

launch:
  folder: submitit_logs/
  partition: gpu1
  nodes: 1
  tasks_per_node: 1
  time: 180
